/* Explanations for the algorithms added with the Tier 3 reorganisation (b = Beginner, a = Intermediate/Advanced). */
export const MORE = {
  'advgraphs/dijkstra': {
    b: { analogy: 'Finding the quickest way from your house to every other town on a map of roads with different lengths. You always walk next to the closest town you have not finished with yet. Once you arrive there by the shortest road, you never need to check it again, and you note whether going THROUGH it makes any neighbour closer.', steps: ['Say the start town is 0 km away and every other town is "far away" (∞).', 'Pick the unfinished town with the smallest distance. That distance is now final.', 'Look at each road from it: is "distance here + road length" shorter than what the neighbour has written down?', 'If yes, update the neighbour (this is called relaxing the road).', 'Repeat until every town is finished.'] },
    a: { summary: 'Greedy single-source shortest paths for non-negative weights: repeatedly settle the unsettled vertex with the smallest tentative distance and relax its outgoing edges.', points: ['Correctness: when u is popped with dist d, any other path to u must leave the settled set through an edge to an unsettled vertex whose tentative distance is ≥ d, and edge weights are ≥ 0, so no path can be shorter (induction on the settled set).', 'Time O((V + E) log V) with a binary heap using lazy deletion (stale entries are skipped, as shown); O(E + V log V) with a Fibonacci heap; O(V²) with an array.', 'Fails with negative edges (a settled vertex could later be improved); use Bellman–Ford or Johnson\'s reweighting.', 'A* is Dijkstra with the key d(v) + h(v); Dijkstra is A* with h = 0.'] },
  },
  'strgeo/kmp': {
    b: { analogy: 'Looking for a word in a long book. A careless reader, after a mismatch, goes back to just after where they started and begins again, re-reading lots of letters. KMP remembers what it has already matched, so it never re-reads the book: it only slides the word forward by exactly as much as is safe.', steps: ['First study the pattern alone and note, for each position, how much of its start also appears at its end (the lps table).', 'Walk through the text comparing letter by letter.', 'On a match, move both along.', 'On a mismatch, use the table to slide the pattern forward; the text pointer does not go back.', 'If the whole pattern matches, report the position.'] },
    a: { summary: 'KMP matches in Θ(n + m) by precomputing the failure function lps[k] = length of the longest proper border of pat[0..k]. After a mismatch at pattern index j the next candidate alignment keeps the last lps[j−1] matched characters.', points: ['Amortised analysis: the text index i never decreases and each iteration either increments i or strictly decreases j; since j ≤ i, the total number of fallbacks is at most n. The lps construction is the same argument on the pattern: Θ(m).', 'Space Θ(m). Unlike the naive Θ(nm) algorithm, no character of the text is examined more than twice.', 'Equivalent to running a DFA built from the pattern; Z-algorithm and Aho–Corasick (many patterns) are related.', 'Rabin–Karp is expected Θ(n + m) with hashing; Boyer–Moore is often sublinear in practice.'] },
  },
  'strgeo/rabinkarp': {
    b: { analogy: 'Instead of comparing two long words letter by letter, you compare their "fingerprints" (a number computed from the letters). If the fingerprints differ the words are different, instantly. If they match, double-check the letters. As the window slides one letter, the fingerprint is updated cheaply instead of being rebuilt.', steps: ['Compute the fingerprint of the pattern.', 'Compute the fingerprint of the first piece of text of the same length.', 'Compare fingerprints. If they match, check the actual letters.', 'Slide one letter: remove the old left letter and add the new right letter to the fingerprint.', 'Repeat to the end of the text.'] },
    a: { summary: 'Polynomial rolling hash H(s) = sum s_i · B^(m−1−i) mod Q. Sliding the window updates H in Θ(1): H\' = (B·(H − s_out·B^(m−1)) + s_in) mod Q.', points: ['Expected Θ(n + m) with a random base/prime (collision probability about m/Q per window); worst case Θ(nm) if many spurious hits need verification.', 'Always verify on hash equality (Las Vegas) or accept a small error probability (Monte Carlo).', 'Extends naturally to multiple patterns (hash set) and 2-D matching.', 'Use a large modulus (about 2^61 − 1) or double hashing to make adversarial collisions impractical.'] },
  },
  'strgeo/hull': {
    b: { analogy: 'Hammer nails into a board at the points, then stretch a rubber band around all of them. The band touches only the outermost nails: that is the convex hull. The algorithm builds the band by walking along the nails from left to right and removing any nail that makes the band bend inward.', steps: ['Sort the points from left to right.', 'Walk through them building the bottom edge; whenever the last three points bend the wrong way, remove the middle one.', 'Walk back from right to left to build the top edge the same way.', 'Join the two edges.'] },
    a: { summary: 'Andrew\'s monotone chain computes the hull in Θ(n log n): sort, then build lower and upper chains with a stack, popping while the turn is not strictly counter-clockwise (cross product ≤ 0).', points: ['Each point is pushed and popped at most once per chain, so after sorting the scan is Θ(n); sorting dominates.', 'Lower bound Ω(n log n) in the algebraic decision-tree model by reduction from sorting; Chan\'s algorithm achieves output-sensitive Θ(n log h).', 'Robustness: the sign of the 2-D cross product should use exact (integer or adaptive) arithmetic; floating point misclassifies nearly collinear triples.', 'Alternatives: Graham scan (angular sort), Jarvis march Θ(nh), QuickHull (expected Θ(n log n), worst case Θ(n²)).'] },
  },
};
