/* Tier 3 explanations (same shape as explanations.js: b = Beginner, a = Intermediate/Advanced). */
export const EXTRA = {
  'heuristic/aostar': {
    b: { analogy: 'Planning a dinner party: for the main course you can EITHER cook (OR choice) OR order in. But "cook" means you must buy ingredients AND prepare them AND set the table (AND: all parts needed). AO* finds the cheapest complete plan, and whenever it learns a part costs more than expected, it updates the cost of every plan that depends on it.', steps: ['Draw the problem as choices (OR) and bundles of required sub-tasks (AND).', 'Follow the currently cheapest plan to an unexplored part and expand it.', 'Work out the new cost of that part.', 'Walk back UP the plan, fixing the cost of every step that depends on it.', 'Stop when the whole plan is made of solved parts.'] },
    a: { summary: 'AO* is best-first search over AND-OR graphs. A solution is a subgraph (a solution graph), not a path: every AND arc chosen must have all its children solved.', points: ['Cost of a node = min over its arcs of the sum of (edge cost + child cost) across the arc\'s AND children; with an admissible heuristic on unexpanded leaves, the first solution found is optimal (for acyclic graphs).', 'Only nodes on the current best partial solution are expanded; revisions propagate bottom-up, which is why the visual is a backwards sweep of cost updates.', 'Used for problem reduction, game-tree style planning and theorem proving.', 'Cycles and shared sub-problems complicate the algorithm (revision can loop); the classical presentation assumes an acyclic graph.'] },
  },
  'advdc/strassen': {
    b: { analogy: 'To multiply two big grids of numbers the usual way you do 8 half-sized multiplications. Strassen found a clever recipe that gets the same answer with only 7 multiplications (plus a few extra additions). Multiplications are costly, additions are cheap, so 7 beats 8.', steps: ['Cut each grid into four equal blocks.', 'Compute seven special products of sums and differences of blocks.', 'Combine them with additions and subtractions to get the four blocks of the answer.', 'Use the same trick inside each product, again and again.'] },
    a: { summary: 'T(n) = 7T(n/2) + Θ(n²). Master Theorem (a = 7, b = 2, f(n) = n² = O(n^(log₂7 − ε))): T(n) = Θ(n^(log₂7)) ≈ Θ(n^2.807).', points: ['The saving is one recursive multiplication; the 18 block additions/subtractions cost only Θ(n²).', 'The practical crossover is large; implementations fall back to the classic algorithm for small blocks, and it needs extra memory and is less numerically stable.', 'Asymptotically faster methods exist (the Coppersmith–Winograd family, exponent about 2.37) but are impractical.', 'It works because matrices over a ring allow subtraction; it needs no commutativity.'] },
  },
  'advdc/closest': {
    b: { analogy: 'Finding the two nearest houses on a map. Split the map in two with a vertical line, find the closest pair on each side, then only check houses near the line, because a closer pair across the line must have both houses close to it.', steps: ['Sort the points left to right and cut them in half.', 'Solve each half separately.', 'Take the smaller of the two answers, d.', 'Only houses within d of the cutting line can form a closer pair across it.', 'Check those few and keep the best.'] },
    a: { summary: 'T(n) = 2T(n/2) + Θ(n) = Θ(n log n), provided the strip is processed in y order without re-sorting from scratch.', points: ['The strip scan is linear because of a packing argument: each d × 2d window holds at most a constant number of points that are pairwise at least d apart, so each point is compared with O(1) successors.', 'Maintaining y-sorted order by merging sub-results (as in merge sort) gives Θ(n log n); re-sorting each strip gives Θ(n log² n).', 'The lower bound is Ω(n log n) in the algebraic decision-tree model.', 'A randomised grid-hashing algorithm achieves expected Θ(n).'] },
  },
  'advdc/fft': {
    b: { analogy: 'A song is a mix of many pure notes. The Fourier transform finds out which notes and how loud. Doing it naively is slow; FFT splits the song into its even and odd samples, solves each half, and stitches the results with a clever pairing so a lot of work is shared.', steps: ['Split the numbers into those at even positions and those at odd positions.', 'Transform each half separately (the same trick again).', 'Combine each pair of results with one addition and one subtraction.', 'Repeat down to single numbers and back up.'] },
    a: { summary: 'FFT computes the DFT y_k = sum_j a_j ω^(jk) in Θ(n log n) via T(n) = 2T(n/2) + Θ(n), exploiting ω^(n/2) = −1 so one twiddle product yields two outputs.', points: ['Polynomial multiplication: evaluate both at n roots of unity (FFT), multiply pointwise, interpolate (inverse FFT): Θ(n log n) versus Θ(n²) schoolbook.', 'n must be a power of two (pad with zeros) for the radix-2 version; other radices and Bluestein\'s algorithm handle general n.', 'Floating-point roundoff limits exactness; use the number-theoretic transform over a finite field for exact integer convolution.', 'In-place iterative versions use a bit-reversal permutation to avoid recursion overhead.'] },
  },
  'netflow/tarjan': {
    b: { analogy: 'In a city of one-way streets, a "neighbourhood" is a group of places where you can drive from any one to any other and back. Tarjan walks the city once, keeps a stack of places visited, and notes how far back up the walk each place can reach. When a place cannot reach any earlier place, everything above it on the stack is one neighbourhood.', steps: ['Walk the graph depth-first, numbering each place as you arrive.', 'Remember the smallest number you can get back to from here.', 'Keep the places in a stack as you go.', 'If you cannot get back above this place, pop the stack down to it: those places form one neighbourhood.'] },
    a: { summary: 'A single DFS computes discovery indices and low-links; a vertex with low[u] = index[u] is the root of an SCC, which is exactly the set popped from the stack.', points: ['Θ(V + E) time and Θ(V) space (stack and arrays).', 'Correctness: a vertex stays on the stack until its SCC root is found; edges to vertices not on the stack lead to already-completed SCCs and are ignored.', 'The condensation graph (SCCs contracted) is a DAG, and SCCs are emitted in reverse topological order.', 'Kosaraju\'s algorithm achieves the same bound with two DFS passes and a transposed graph.'] },
  },
  'netflow/johnson': {
    b: { analogy: 'Some roads pay you to drive on them (negative cost), which breaks the usual "shortest route" trick. Johnson gives every town a "price tag" so that, after adjusting, no road pays you any more, yet the best route between any two towns stays the same. Then the fast normal method works from every town.', steps: ['Add a helper town connected to all towns for free.', 'Find the cheapest distance from the helper to each town (this method can handle negative roads).', 'Use those distances to adjust every road\'s cost so none is negative.', 'Run the fast shortest-route method from every town.', 'Undo the adjustment to get the true distances.'] },
    a: { summary: 'All-pairs shortest paths with negative edges: Bellman–Ford potentials h make reduced weights w\'(u,v) = w(u,v) + h(u) − h(v) ≥ 0 (triangle inequality), then run Dijkstra from each vertex.', points: ['A path from a to b changes by exactly h(a) − h(b), independent of the path, so shortest paths are preserved.', 'Time O(VE + V² log V) with Fibonacci heaps (O(VE log V) with binary heaps); this beats Floyd–Warshall Θ(V³) when E = o(V²).', 'Negative cycles are detected by Bellman–Ford, in which case shortest paths are undefined.', 'Space Θ(V²) for the distance matrix.'] },
  },
  'netflow/fordfulkerson': {
    b: { analogy: 'Water pipes from a tank to a town, each pipe with a maximum rate. Keep finding any route that still has room, and push as much water as the narrowest pipe on that route allows. If you later realise an earlier push was a mistake, "backward pipes" let you send some water back.', steps: ['Start with no water flowing.', 'Find any route from source to sink where every pipe still has spare room.', 'Push as much as the tightest pipe on the route allows.', 'Update the spare room (and add backwards room so mistakes can be undone).', 'Repeat until no such route exists. The total pushed is the maximum.'] },
    a: { summary: 'Repeatedly augment along s–t paths in the residual graph. The flow is maximum iff no augmenting path exists (max-flow min-cut theorem: the maximum flow value equals the minimum cut capacity).', points: ['With integer capacities each augmentation adds at least 1, so O(E · |f*|) time; the running time is pseudo-polynomial and can be bad when paths are chosen poorly.', 'Edmonds–Karp (BFS shortest augmenting path) runs in O(V·E²) independent of capacities; Dinic\'s algorithm improves this to O(V²E).', 'Backward residual edges encode the ability to cancel flow; without them greedy augmentation can get stuck below the optimum.', 'Applications: bipartite matching, project selection, image segmentation via min-cut.'] },
  },
  'advdp/mcm': {
    b: { analogy: 'Multiplying a stack of matrices: you may do it in any grouping, but some groupings need far less arithmetic. Try every place to put the "first bracket", and remember the best cost for every shorter sub-stack, so each sub-stack is only worked out once.', steps: ['The cost of a single matrix is 0.', 'For each stack length 2, 3, 4…: look at every sub-stack of that length.', 'Try every place to split it in two.', 'Cost = left cost + right cost + the cost to multiply the two results.', 'Keep the cheapest split.'] },
    a: { summary: 'Interval DP: dp[i][j] = min over i ≤ k < j of dp[i][k] + dp[k+1][j] + p(i−1)·p(k)·p(j).', points: ['Θ(n²) subproblems × Θ(n) transitions = Θ(n³) time, Θ(n²) space; the number of parenthesisations is the Catalan number C(n−1), which is exponential, so brute force is hopeless.', 'Evaluation order: by increasing chain length (diagonals) so both sub-intervals are ready.', 'Store the argmin split to reconstruct the parenthesisation.', 'Hu–Shing achieves Θ(n log n) but is far more complex; the same interval-DP pattern solves optimal BST, polygon triangulation and burst balloons.'] },
  },
  'advdp/bitmask': {
    b: { analogy: 'A delivery driver must visit every house once and return home. Instead of trying every order (a huge number), remember, for each SET of houses already visited and the house you are standing at, the shortest distance so far. A row of on/off switches (bits) records which houses are done.', steps: ['Use one switch per house: on means visited.', 'Store the best distance for every combination of switches and current house.', 'From each stored state, try moving to every unvisited house.', 'Keep the shorter distance for the new state.', 'At the end, add the way home and take the smallest.'] },
    a: { summary: 'Held–Karp: dp[mask][i] = min cost of a path from city 0 visiting exactly the set mask and ending at i. Transition: dp[mask | {j}][j] = min(dp[mask][i] + d(i, j)).', points: ['Θ(n · 2ⁿ) states × Θ(n) transitions = Θ(n² · 2ⁿ) time and Θ(n · 2ⁿ) space: exponential, but far below the Θ(n!) of brute force (for n = 20 that is roughly 4·10⁸ versus 2·10¹⁸).', 'Bitmasks make subset membership, insertion and iteration Θ(1) word operations, and integer order guarantees dependencies are computed first.', 'TSP is NP-hard; no polynomial algorithm is known, so exact solutions are practical only to n of about 20–25.', 'The same subset-DP pattern solves assignment, Hamiltonian path and set-cover variants for small n.'] },
  },
  'advdp/treedp': {
    b: { analogy: 'Choosing friends to invite to a party from a family tree where no one invites their direct parent or child. For every person, work out two numbers: the best party if THEY come, and the best party if they DON\'T. Combine children first, then parents.', steps: ['Start at the leaves: a leaf either comes (its value) or does not (0).', 'For a parent who comes: add the "does not come" value of each child.', 'For a parent who does not come: add the better of the two values of each child.', 'The best party is the better of the two values at the root.'] },
    a: { summary: 'Post-order DP over a rooted tree: each vertex keeps a small state vector summarising its subtree, and children are merged into their parent.', points: ['Θ(n) time and Θ(h) stack; each edge is processed once.', 'It works because the child subtrees are independent given the parent\'s state, which a general graph does not guarantee (treewidth generalises this idea).', 'Typical states: (take/skip), (depth/size), rerooting; extend with dp[u][k] for knapsack-on-tree in Θ(n²).', 'Use an explicit stack for very deep trees to avoid recursion overflow.'] },
  },
};
