/* Adaptive Explanation Engine content.
   b = Beginner: real-world analogy + plain-language steps.
   a = Intermediate/Advanced: precise statement, complexity, proof sketch, trade-offs.
   Everything is plain text (rendered as React text nodes). */

export const KIND_HINTS = {
  b: {
    info: 'We are just setting things up. Nothing is decided yet.',
    compare: 'The computer is looking at two things to decide what to do next, like checking which of two boxes is heavier.',
    swap: 'Two things trade places because they were in the wrong order.',
    divide: 'The big problem is being cut into smaller pieces that are easier to handle.',
    merge: 'Two tidy piles are being combined into one tidy pile.',
    pivot: 'One item is picked as a reference point: smaller things go on one side, bigger on the other.',
    discard: 'A whole chunk of possibilities is crossed off at once because we now know the answer cannot be there.',
    move: 'A marker slides along to a new spot, because the old spot cannot help any more.',
    conflict: 'This choice breaks a rule, so it cannot be used.',
    place: 'A choice is made, or a new candidate is added to the to-do list, and written down (for now).',
    remove: 'The last choice led nowhere, so it is taken back. This is the "undo" of backtracking.',
    deadend: 'Every option here failed, so we must go back to an earlier decision.',
    pick: 'The next item is chosen by the rule of the algorithm (best option, oldest, newest, smallest f...).',
    reject: 'This option is skipped because it does not fit.',
    match: 'Things agree, so we can build on what we already know.',
    trace: 'Now we walk backwards through the table to read off the actual answer.',
    fail: 'We looked everywhere and the answer is not there.',
    done: 'The job is finished. Check the result.',
  },
  a: {
    info: 'Initialisation: establish the invariant that the rest of the algorithm maintains.',
    compare: 'A Θ(1) comparison or table lookup. Count these: the total number of comparisons is what the time bound measures.',
    swap: 'A Θ(1) exchange. Swaps (or writes) are the other cost metric, and matter when writes are expensive.',
    divide: 'Divide step: partition the instance into subproblems. The recurrence is T(n) = aT(n/b) + f(n).',
    merge: 'Combine step: Θ(n) work for two sorted runs of total length n, which gives the f(n) in the recurrence.',
    pivot: 'Pivot selection determines the split balance; a bad pivot makes the recursion depth linear rather than logarithmic.',
    discard: 'Search-space reduction: each step removes a constant fraction of candidates, which yields the logarithmic bound.',
    move: 'Pointer advance justified by the loop invariant: the discarded element cannot be part of any better solution.',
    conflict: 'Constraint check (prune). Pruning early shrinks the explored part of the exponential search tree.',
    place: 'A state or candidate is added to the working structure (partial solution, stack, queue or open list). The peak size of that structure bounds the space used.',
    remove: 'Undo: restore the state before the choice. Skipping this corrupts sibling branches (state must be restored exactly).',
    deadend: 'All children failed: the subtree is exhausted and the search backtracks to the parent.',
    pick: 'Selection step: the candidate is chosen by the rule of the algorithm (greedy choice, priority order, traversal order). Correctness rests on the invariant that rule maintains (e.g. the greedy-choice property).',
    reject: 'Candidate dismissed: infeasible, dominated, or already seen. Testing this early is what keeps the search small.',
    match: 'Recurrence case with equal elements: dp[i][j] = dp[i-1][j-1] + 1. Optimal substructure in action.',
    trace: 'Reconstruction by following the argmax decisions backwards: Θ(m + n) extra time, no extra table.',
    fail: 'Termination without success: the invariant shows no solution exists in the remaining space.',
    done: 'Postcondition reached. The result follows from the invariant plus the loop exit condition.',
  },
};

const E = {};
const add = (id, b, a) => { E[id] = { b, a }; };

/* ---------- Complexity ---------- */
add('complexity/growth',
  { analogy: 'Imagine washing dishes. Washing ONE extra plate always costs the same (constant). But if every plate has to be compared with every other plate, each new plate makes much more work than the last. Big-O is the name for HOW the work grows as the pile grows.', steps: ['Pick a size n (how many plates).', 'Count the basic steps the method needs for that n.', 'Plot n against steps: a flat line is great, a steep climb is a warning.', 'Watch which curves shoot off the chart: those methods stop being usable very quickly.'] },
  { summary: 'Asymptotic classes order functions by dominant growth. For large n, the ranking 1 ≺ log n ≺ n ≺ n log n ≺ n² ≺ 2ⁿ ≺ n! holds regardless of constants.', points: ['Polynomial vs exponential: n^k = o(2ⁿ) for every fixed k, so a single extra input item can double an exponential algorithm\'s work.', 'n log n is the information-theoretic lower bound for comparison sorting (log₂(n!) = Θ(n log n)).', 'Constants and lower-order terms are dropped by definition, but they decide practice for small n (an O(n²) insertion sort beats O(n log n) on tiny arrays).', 'Compare algorithms by growth rate first, constant factors second, memory behaviour third.'] });
add('complexity/theta',
  { analogy: 'Suppose a taxi fare is always somewhere between 2× and 3× the distance. Then "the fare grows like the distance" is a tight description. O gives only a ceiling, Ω only a floor, and Θ says the ceiling and the floor are the same shape.', steps: ['Big-O: find a curve that stays ABOVE yours (a ceiling).', 'Big-Omega: find a curve that stays BELOW yours (a floor).', 'If one shape (same g) works as both ceiling and floor, you have Θ, a tight fit.', 'Check a too-small shape (fails the ceiling) and a too-big shape (a loose, but true, ceiling).'] },
  { summary: 'f ∈ O(g) iff ∃ c>0, n₀ ∀ n≥n₀: f(n) ≤ c·g(n). f ∈ Ω(g) iff the reverse inequality holds. f ∈ Θ(g) iff both hold, i.e. f ∈ O(g) ∩ Ω(g).', points: ['For f(n) = an² + bn: an² ≤ f(n) ≤ (a+b)n² for n ≥ 1, so f ∈ Θ(n²) with c₁ = a, c₂ = a + b, n₀ = 1.', 'Limit test: if lim f/g = L with 0 < L < ∞ then f ∈ Θ(g); L = 0 gives f ∈ o(g); L = ∞ gives f ∈ ω(g).', 'O and Ω describe functions, not cases: "worst case" and "best case" pick which function (input family) you analyse.', 'Saying "the algorithm is O(n²)" for a Θ(n) algorithm is true but uninformative; prefer the tight bound.'] });

/* ---------- Sorting ---------- */
add('sorting/bubble',
  { analogy: 'Picture kids in a line sorting themselves by height. Each pair of neighbours checks: "am I taller than the one next to me?" If so, they swap. After one walk down the line, the tallest kid has bubbled to the end.', steps: ['Look at the first two neighbours.', 'If they are in the wrong order, swap them.', 'Move one step along and repeat to the end of the line.', 'The biggest is now at the end. Repeat for the shorter line that remains.', 'If a whole walk needed no swaps, everyone is already in order: stop.'] },
  { summary: 'Adjacent-swap comparison sort. After pass i, the i largest elements occupy their final positions (loop invariant), so the active region shrinks by one each pass.', points: ['Comparisons: (n−1) + (n−2) + … + 1 = n(n−1)/2 = Θ(n²) in the worst and average cases; best case Θ(n) with the swapped-flag early exit.', 'Swaps equal the number of inversions: Θ(n²) worst case, 0 when sorted.', 'Stable and in-place (O(1) extra space).', 'Trade-off: simple and adaptive on nearly-sorted data, but dominated by insertion sort in practice and by O(n log n) sorts for large n.'] });
add('sorting/insertion',
  { analogy: 'This is how most people sort playing cards in their hand. You pick up one new card, slide it left past every bigger card, and drop it into the gap. The cards on your left are always already in order.', steps: ['Treat the first item as a sorted pile of one.', 'Take the next item (the "key").', 'Slide the bigger items on its left one place right.', 'Drop the key into the gap that opens.', 'Repeat until every item has been inserted.'] },
  { summary: 'Maintains the invariant that a[0..i−1] is sorted; each iteration inserts a[i] into its correct position by shifting larger elements right.', points: ['Time: Θ(n + I) where I is the number of inversions, so Θ(n) on sorted input and Θ(n²) worst case (reverse sorted).', 'Stable, in-place, online (can sort data as it arrives).', 'Binary search can find the insertion point in O(log n) comparisons but shifting still costs O(n).', 'Used as the base case inside hybrid sorts (Timsort, introsort) because the constant factor is tiny for small n.'] });
add('sorting/merge',
  { analogy: 'Imagine sorting a huge pile of exam papers. Split the pile in half again and again until each pile has one paper (one paper is already sorted!). Then merge neighbouring piles by always taking the smaller top paper. Merging two sorted piles is quick.', steps: ['Split the list into two halves.', 'Keep splitting until every piece has just one item.', 'Merge two neighbouring pieces: compare their front items and take the smaller.', 'Keep merging bigger and bigger sorted pieces until one pile remains.'] },
  { summary: 'Divide and conquer: T(n) = 2T(n/2) + Θ(n). By the Master Theorem (a = b = 2, f(n) = Θ(n^{log_b a})), T(n) = Θ(n log n).', points: ['Time is Θ(n log n) in all cases (best, average, worst): the recursion tree has log₂ n levels, each doing Θ(n) merge work.', 'Space: Θ(n) auxiliary for merging arrays (Θ(log n) stack); linked-list variants merge in O(1) extra space.', 'Stable if ties take the left element first.', 'Trade-off: optimal comparison count and predictable, cache-friendly sequential access (good for external sorting), but the extra memory is a drawback versus in-place quicksort.'] });
add('sorting/quick',
  { analogy: 'Pick one person in a crowd as the "reference". Everyone shorter stands on their left, everyone taller on their right. That person is now exactly where they belong. Repeat the idea separately for the left group and the right group.', steps: ['Choose a pivot (here: the last item).', 'Walk through the rest: move smaller items to the front zone.', 'Put the pivot just after the small zone. It is now in its final place.', 'Do the same for the group on the left and the group on the right.'] },
  { summary: 'Partition around a pivot so that left ≤ pivot < right, then recurse. The pivot is placed in its final sorted position by each partition.', points: ['Expected time Θ(n log n) (random pivot or random input); worst case Θ(n²) when partitions are maximally unbalanced (e.g. last-element pivot on sorted input).', 'Recurrence: T(n) = T(k) + T(n−k−1) + Θ(n); balanced splits give n log n, the extreme split gives n².', 'In-place with O(log n) expected stack (recurse on the smaller side first to guarantee it).', 'Not stable. In practice often fastest due to cache locality; mitigations: random or median-of-three pivots, introsort fallback to heapsort.'] });

/* ---------- Searching ---------- */
add('searching/binary',
  { analogy: 'Guess-my-number: I am thinking of a number from 1 to 100. You always guess the middle, and I say "higher" or "lower". Each answer throws away half of the numbers, so you find it in about 7 guesses.', steps: ['Look at the middle item of the part you are still searching.', 'If it is the target, you are done.', 'If the target is bigger, throw away the middle and everything left of it.', 'If it is smaller, throw away the middle and everything right of it.', 'Repeat on what is left. If nothing is left, the target is not there.'] },
  { summary: 'Maintains the invariant that the target, if present, lies in a[lo..hi]. Each iteration halves the interval.', points: ['At most ⌊log₂ n⌋ + 1 comparisons: T(n) = T(n/2) + Θ(1) = Θ(log n); space Θ(1) iteratively.', 'Requires random access and sorted data; on a linked list it degrades to Θ(n).', 'Overflow trap: use mid = lo + (hi − lo) / 2 in fixed-width integer languages.', 'Variants (lower_bound / upper_bound) find insertion points and boundaries; the idea generalises to "binary search on the answer" for any monotone predicate.'] });
add('searching/linear',
  { analogy: 'Looking for your keys by checking every pocket, one after another, until you find them or run out of pockets.', steps: ['Start at the first item.', 'Check: is it what you want?', 'If not, move to the next item.', 'Stop when you find it, or when there are no more items.'] },
  { summary: 'Sequential scan: examine elements until a match or the end.', points: ['Worst and average cases Θ(n) comparisons (average n/2 for a present target); best case Θ(1).', 'No preconditions: works on unsorted data and on structures without random access.', 'Space Θ(1).', 'Trade-off: for a single query on unsorted data it is optimal; for many queries, sorting once (Θ(n log n)) or hashing beats repeated scans.'] });

/* ---------- Two pointers ---------- */
add('twopointers/twosum',
  { analogy: 'Two people start at opposite ends of a sorted row of numbers. If their numbers add up to too little, the left person steps right to a bigger number. If too much, the right person steps left to a smaller number. They squeeze together until they hit the target.', steps: ['Put one marker on the smallest number and one on the biggest.', 'Add the two numbers.', 'Too small? Move the left marker right (to a bigger number).', 'Too big? Move the right marker left (to a smaller number).', 'Stop when the sum matches, or the markers meet.'] },
  { summary: 'On sorted input, the pair search is reduced from Θ(n²) to Θ(n) by exploiting monotonicity of the sum in each pointer.', points: ['Invariant: if a valid pair (i, j) exists, then l ≤ i and j ≤ r. Proof: if sum(l, r) < target, then for every j\' ≤ r, a[l] + a[j\'] ≤ a[l] + a[r] < target, so l cannot be in any answer and is safely discarded (symmetric for r).', 'Each iteration discards one index, so at most n − 1 iterations: Θ(n) time, Θ(1) space.', 'Sorting first costs Θ(n log n); a hash-set approach is Θ(n) time but Θ(n) space and works unsorted.', 'The same monotonicity argument underlies 3-sum (Θ(n²)) and many partition problems.'] });
add('twopointers/palindrome',
  { analogy: 'Read a word from both ends at the same time, like two people walking toward each other along a corridor. If every pair of letters they stand on matches, the word reads the same both ways.', steps: ['Put one finger on the first letter and one on the last.', 'Compare the two letters.', 'If they differ, it is NOT a palindrome.', 'If they match, move both fingers one step inward.', 'If the fingers meet or cross with no mismatch, it IS a palindrome.'] },
  { summary: 'A string is a palindrome iff s[i] = s[n−1−i] for all i < n/2; two pointers check exactly those pairs.', points: ['Time Θ(n) (⌊n/2⌋ comparisons), space Θ(1); exits at the first mismatch.', 'Preprocessing (case folding, filtering non-alphanumerics) can be done on the fly with pointer skipping to keep Θ(1) extra space.', 'Longest palindromic substring generalises this by expanding from each centre (Θ(n²)) or Manacher\'s algorithm (Θ(n)).'] });
add('twopointers/water',
  { analogy: 'Two walls hold water. The water can only be as high as the SHORTER wall. If you move the taller wall inward you can only lose width and still be stuck at the short wall\'s height. So you always move the shorter wall and hope to find a taller one.', steps: ['Start with the two outermost walls.', 'Water area = shorter wall height × distance between walls.', 'Remember the best area seen.', 'Move the shorter wall inward (the other move can never help).', 'Stop when the walls meet.'] },
  { summary: 'Greedy two-pointer search over all pairs (i, j) in Θ(n) instead of Θ(n²). Area(i, j) = min(h_i, h_j) · (j − i).', points: ['Correctness (exchange argument): suppose h_l ≤ h_r. Any pair (l, k) with k < r has width smaller and height ≤ h_l, so area ≤ the current area; hence l can be discarded without losing the optimum.', 'Time Θ(n), space Θ(1).', 'Ties can move either pointer; both choices preserve the argument.', 'Contrast with "trapping rain water" where prefix/suffix maxima or a monotone stack are needed.'] });

/* ---------- Trees ---------- */
add('trees/inorder',
  { analogy: 'Reading a family tree where, for each person, you first read everything about their left side, then the person, then their right side. For a number tree where smaller numbers go left, that reads the numbers from smallest to biggest.', steps: ['Go as far left as possible.', 'When you cannot go left, say the number.', 'Then go to the right child and repeat the same idea.', 'When both sides are done, go back up.'] },
  { summary: 'Left–Node–Right depth-first traversal. On a binary search tree it yields keys in non-decreasing order.', points: ['Time Θ(n): each node is entered once; space Θ(h) call stack (h = height; Θ(n) for a skewed tree, Θ(log n) if balanced).', 'Iterative form uses an explicit stack; Morris traversal achieves Θ(1) extra space by temporarily threading the tree.', 'Correctness on BST: by the BST property all left-subtree keys < node < all right-subtree keys, so the output is sorted by induction.', 'Used for sorted iteration, validating a BST, and k-th smallest queries.'] });
add('trees/preorder',
  { analogy: 'Writing a book\'s table of contents: you write the chapter title FIRST, then its sub-chapters on the left, then those on the right. The boss gets announced before the team.', steps: ['Say the current number straight away.', 'Then go left and do the same.', 'Then go right and do the same.', 'Go back up when both sides are finished.'] },
  { summary: 'Node–Left–Right depth-first traversal: a node is emitted before any descendant.', points: ['Θ(n) time, Θ(h) space.', 'Root is always first, so pre-order (with null markers) serialises a tree and can rebuild it; with a BST, the pre-order alone determines the tree.', 'Natural for copying a tree and for prefix expression output.', 'Iterative version: push right child then left child on a stack.'] });
add('trees/postorder',
  { analogy: 'Closing down a company: the managers can only be dismissed after all their team has left. So you handle the left team, then the right team, and the boss last.', steps: ['Go left and finish that whole side.', 'Go right and finish that whole side.', 'Only now say the current number.', 'The root is always the very last one.'] },
  { summary: 'Left–Right–Node depth-first traversal: children are processed before their parent.', points: ['Θ(n) time, Θ(h) space.', 'The right tool when a node\'s result depends on its subtrees: deleting a tree, computing heights/sizes, evaluating expression trees, tree DP.', 'Reverse post-order of a DAG DFS gives a topological order.', 'Iterative version needs two stacks or a last-visited pointer, which is why recursion is clearer here.'] });
add('trees/levelorder',
  { analogy: 'People leaving a building floor by floor: everyone on floor 1 first, then floor 2, and so on. A queue (first come, first served) makes this happen naturally.', steps: ['Put the root in a waiting line (a queue).', 'Take the first person out of the line and say their number.', 'Put their left and right children at the back of the line.', 'Repeat until the line is empty.'] },
  { summary: 'Breadth-first traversal using a FIFO queue; visits nodes in non-decreasing depth.', points: ['Θ(n) time; space Θ(w) where w is the maximum width (up to ~n/2 for a complete tree), versus Θ(h) for DFS.', 'The FIFO discipline guarantees all depth-d nodes are dequeued before any depth-(d+1) node: shortest-path layering for unweighted structures.', 'To group by level, process queue.size() nodes per round.', 'Replace the queue by a stack and you get a (reverse-child) pre-order DFS: the data structure alone determines the traversal.'] });

/* ---------- Graphs ---------- */
add('graphs/bfs',
  { analogy: 'Drop a stone in a pond: ripples spread outward one ring at a time. BFS visits all neighbours first (ring 1), then their neighbours (ring 2), and so on. The "visited" list is like a guest list: nobody is invited twice, so you never walk in circles.', steps: ['Write the start node on the visited list and put it in a waiting line.', 'Take the first node from the line.', 'Look at each neighbour. If it is not on the visited list, write it down and add it to the back of the line.', 'Repeat until the line is empty.'] },
  { summary: 'BFS explores a graph in layers using a FIFO queue and a visited set; discovery time of v is dist(s, v) in edges.', points: ['Θ(V + E) time with adjacency lists; Θ(V) space for the queue and visited set.', 'Marking at ENQUEUE time (not dequeue time) bounds the queue by V and prevents duplicates; this is exactly what the visited set does on cyclic graphs.', 'Yields shortest paths (fewest edges) in unweighted graphs; BFS tree edges form a shortest-path tree.', 'Fails for weighted graphs (use Dijkstra); 0–1 BFS handles weights in {0, 1} with a deque.'] });
add('graphs/dfs',
  { analogy: 'Exploring a maze by always taking a new corridor and going as deep as possible. When you hit a dead end (or somewhere you have already been), you step back to the last junction and try another path. A chalk mark on every visited room (the visited set) stops you going around in circles.', steps: ['Put the start node on a stack (a pile where you take from the top).', 'Take the top node. If it was already visited, skip it.', 'Otherwise mark it visited and push its unvisited neighbours.', 'Repeat until the stack is empty.'] },
  { summary: 'DFS explores as deep as possible before backtracking, via an explicit stack (or recursion) plus a visited set.', points: ['Θ(V + E) time, Θ(V) space (stack depth up to V).', 'Edge classification during DFS (tree, back, forward, cross) detects cycles (back edge) and underlies topological sort, SCCs (Tarjan/Kosaraju) and articulation points.', 'Without the visited set, DFS on a cyclic graph does not terminate.', 'Does NOT find shortest paths; the path to a node depends on neighbour ordering.'] });

/* ---------- Backtracking ---------- */
add('backtracking/nqueens',
  { analogy: 'Seating guests at a table where some guests refuse to sit near each other. You seat people one by one. When someone cannot be seated anywhere without a fight, you go back and move the person you seated before them, and try again.', steps: ['Put a queen on the first row in the first safe column.', 'Move to the next row and try to place a queen so that nobody attacks anybody.', 'If a row has no safe square, remove the queen from the row above and try its next column.', 'If all rows get a queen, you found a solution.'] },
  { summary: 'Depth-first search of the solution tree with constraint pruning: extend a partial placement row by row, abandoning a branch the moment a constraint fails.', points: ['Unpruned search space is n^n (or n! with one queen per column); pruning removes most of it, but the worst case remains exponential.', 'Conflict check is Θ(1) with column/diagonal bitsets (columns, r−c, r+c) or Θ(n) by scanning placed queens (as shown).', 'Space Θ(n) for the board state plus recursion depth; the "remove" step restores state so siblings start clean.', 'Improvements: bitmask solvers, symmetry reduction (the number of solutions grows roughly like ~(0.14n)^n), or constraint propagation / min-conflicts for large n.'] });

/* ---------- Greedy ---------- */
add('greedy/activity',
  { analogy: 'You want to see as many films as possible at a festival. The trick: always pick the film that ENDS earliest among those you can still make. That leaves the most time for the next one.', steps: ['Sort all activities by when they finish.', 'Take the first one (it finishes earliest).', 'Look at the next activity: does it start after the last chosen one ended?', 'If yes, take it. If no, skip it.', 'Keep going to the end of the list.'] },
  { summary: 'Interval scheduling maximisation: sort by finish time and greedily take every compatible interval. The result is a maximum-size set of pairwise non-overlapping intervals.', points: ['Time Θ(n log n) for sorting plus Θ(n) for the scan; space Θ(1) extra.', 'Greedy-choice property (exchange argument): let g be the earliest-finishing activity. Any optimal schedule can swap its first activity for g without creating a conflict, since g finishes no later. Optimal substructure then reduces the problem to the activities starting after g.', 'Other greedy keys fail: earliest start, shortest duration and fewest conflicts each have counter-examples.', 'The weighted version (maximise total weight) is NOT solvable greedily; it needs dynamic programming (Θ(n log n) with binary search).'] });

/* ---------- DP ---------- */
add('dp/lcs',
  { analogy: 'Two friends compare their holiday photo albums to find the longest list of places they visited in the same order (not necessarily one right after another). The table remembers the best answer for every pair of "first few photos", so nothing is worked out twice.', steps: ['Make a grid: one string along the top, one down the side.', 'If the two letters match, take the diagonal answer and add 1.', 'If they differ, take the better of the cell above and the cell to the left.', 'The bottom-right cell is the length of the answer.', 'Walk back through the grid to read the letters.'] },
  { summary: 'dp[i][j] = LCS length of X[1..i], Y[1..j]. Recurrence: dp[i][j] = dp[i−1][j−1] + 1 if x_i = y_j, else max(dp[i−1][j], dp[i][j−1]).', points: ['Θ(mn) time and space; space drops to Θ(min(m, n)) for the length alone (two rows), but the traceback then needs Hirschberg\'s divide-and-conquer.', 'Optimal substructure: an LCS of prefixes ends either with a matched pair or drops one end character.', 'Overlapping subproblems: naive recursion is Θ(2^{m+n}); memoising the Θ(mn) distinct (i, j) pairs removes that.', 'Related: edit distance, diff tools, sequence alignment (Needleman–Wunsch).'] });
add('dp/knapsack',
  { analogy: 'You are packing a backpack with a weight limit. For each item you ask: is the bag better with it or without it? The table remembers the best loot for every combination of "first few items" and "bag size", so you never repeat your thinking.', steps: ['Rows are items, columns are bag sizes.', 'For each cell: the best you can do WITHOUT this item is the number above.', 'If the item fits, also compute: its value + the best for the remaining space (row above).', 'Keep the larger of the two.', 'The bottom-right cell is the best total. Walk back to see which items you took.'] },
  { summary: '0/1 knapsack: dp[i][c] = max(dp[i−1][c], dp[i−1][c − w_i] + v_i) when w_i ≤ c, else dp[i−1][c].', points: ['Θ(nW) time and space; Θ(W) space with a 1-D array iterated over capacity in DESCENDING order (so each item is used at most once).', 'Pseudo-polynomial: W is the numeric value, not the input length; the problem is NP-hard in general (weakly NP-complete).', 'Reading from the row above is what enforces "each item at most once"; reading the current row would give the unbounded knapsack.', 'Approximations: an FPTAS exists by scaling values.'] });
add('dp/coins',
  { analogy: 'Making change with the fewest coins. To make 10p you ask: if I use one 1p coin, how few coins do I need for 9p? If I use a 5p coin, how few for 5p? If I use a 6p coin, how few for 4p? Pick the best, and remember the answers for every smaller amount.', steps: ['Start with "0 pence needs 0 coins".', 'For each amount, try every coin that is not bigger than the amount.', 'Look up how many coins the leftover amount needs, and add 1.', 'Keep the smallest total.', '∞ means "impossible so far".'] },
  { summary: 'Unbounded-supply min-coins: dp[a] = 1 + min over coins c ≤ a of dp[a − c], with dp[0] = 0 and dp[a] = ∞ if unreachable.', points: ['Θ(A · k) time (A = amount, k = coins), Θ(A) space; pseudo-polynomial and NP-hard in general.', 'Greedy "largest coin first" is optimal only for canonical coin systems (e.g. standard currencies); with {1, 5, 6} and A = 10 greedy gives 6+1+1+1+1 (5 coins) but the optimum is 5+5 (2 coins).', 'Initialise with ∞, not 0, otherwise unreachable amounts look free.', 'Counting the number of ways (not the minimum) uses a different recurrence and loop order.'] });

/* ---------- Heuristic search ---------- */
add('heuristic/astar',
  { analogy: 'You are walking through a city to a landmark you can see in the distance. g is how far you have ALREADY walked; h is your eyeball guess of how far is LEFT as the crow flies. You always continue from the spot with the smallest total (g + h), so you head towards the landmark but still notice when a street is a dead end.', steps: ['Every square gets g (steps so far), h (guess to the goal) and f = g + h.', 'Keep a to-do list (open list) sorted by f.', 'Take the best square from the list and mark it done.', 'Look at its neighbours: add new ones, or update ones you can now reach more cheaply.', 'When the goal comes off the list, follow the "came from" trail back to get the path.'] },
  { summary: 'Best-first search ordered by f(n) = g(n) + h(n). With an admissible h (h ≤ true remaining cost) A* returns an optimal path; with a consistent h (h(n) ≤ c(n, n\') + h(n\')) each node is expanded at most once and f is non-decreasing along paths.', points: ['Optimality proof sketch: when the goal is popped with f = g*, any node on an optimal path still in the open list has f ≤ g* (admissibility), so it would have been popped first; hence no cheaper path remains.', 'h = 0 reduces A* to Dijkstra; a perfect h expands only the optimal path. A larger (still admissible) h never expands more nodes, up to tie-breaking.', 'Time and space O(b^d) in the worst case; memory is usually the bottleneck (IDA* and SMA* trade time for memory).', 'Manhattan distance is admissible and consistent on a 4-connected unit-cost grid; weighted A* (f = g + w·h, w > 1) is faster but only w-suboptimal.'] });

import { EXTRA } from './explanationsAdvanced.js';
import { MORE } from './explanationsMore.js';
Object.assign(E, EXTRA, MORE);

export const EXPLAIN = E;

/** Lookup by `module/algo`, falling back to any entry for the same algorithm id (algorithms moved between modules). */
export function explainFor(moduleId, algoId) {
  return E[moduleId + '/' + algoId] || E[Object.keys(E).find((k) => k.endsWith('/' + algoId))] || null;
}
